_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/sft_grpo/trainer.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.52.4
            "8":
                - 5
            "12": 0.19.11
            "13": linux-aarch64
batch_size:
    value: 2
dataset:
    value: cdreetz/triton-sft-dataset
learning_rate:
    value: 5e-05
model_name:
    value: Qwen/Qwen2.5-1.5B-Instruct
num_epochs:
    value: 3
